stBM(2,"basic1",[0,"","","images/blank.gif",0,"left","default","hand",0,0,-1,-1,-1,"none",0,"#CCCCCC","transparent","","repeat",1,"images/expand_f.gif","expand_uf.gif",9,9,1,"images/line_def0.gif","images/line_def1.gif","images/line_def2.gif","images/line_def3.gif",1,0,3,1,"center",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["住房专项维修资金管理信息系统","#","_self","","","images/file_c.gif","images/file_c.gif",20,20,"9pt 'Verdana','Arial'","#000000","none","transparent","","no-repeat","9pt 'Verdana','Arial'","#666666","none","transparent","","no-repeat","bold 9pt 'Verdana'","#000000","none","transparent","","no-repeat","9pt 'Verdana'","#000000","none","transparent","","no-repeat",1,0,"left","middle",160,0]);
stIT("p0i1",["计息模块",,,,,"images/file_f.gif","images/file_uf.gif",,,,,,,,,,"#000000",,,,"repeat-x",,,,,,,,,,,,,,,,,0],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["内容分类1",,,,,,,,,,,,,,,,"#666666",,,,"no-repeat","9pt 'Verdana'",,,,,,,"#666666"],"p0i1");
stBS("p2",[],"p0");
stIT("p2i0",["Sothink DHTMLMenu",,,,,"images/file_c.gif","images/file_c.gif"],"p1i0");
stIT("p2i1",["Sothink Tree Menu"],"p2i0");
stES();
stIT("p1i1",["内容分类2"],"p1i0");
stBS("p3",[],"p0");
stIT("p3i0",["Sothink Swf Quicker"],"p2i0");
stIT("p3i1",["Sothink Glanda"],"p2i0");
stIT("p3i2",["Sothink Swf Decompiler"],"p2i0");
stES();
stIT("p1i2",["Java Applet"],"p1i0");
stBS("p4",[],"p0");
stIT("p4i0",["Sothink SlidingMenu"],"p2i0");
stIT("p4i1",["Sothink Coolmenu"],"p2i0");
stIT("p4i2",["Sothink Coolbutton"],"p2i0");
stIT("p4i3",["Sothink Cooltext"],"p2i0");
stIT("p4i4",["Java Decompiler"],"p2i0");
stES();
stES();
stIT("p0i2",["业主管理模块"],"p0i1");
stBS("p5",[],"p0");
stIT("p5i0",["Premade Templates"],"p2i0");
stIT("p5i1",["Customization",,,,,,,,,,,,,,,,"666666"],"p2i0");
stES();
stIT("p0i3",["系统维护"],"p0i1");
stBS("p6",[],"p0");
stIT("p6i0",["Order in US Dollars"],"p5i1");
stIT("p6i1",["Order in Euros"],"p5i1");
stIT("p6i2",["Order Help"],"p5i1");
stES();
stIT("p0i4",["缴存模块"],"p0i1");
stBS("p7",[],"p0");
stIT("p7i0",["Products Support"],"p5i1");
stIT("p7i1",["Forum"],"p5i1");
stIT("p7i2",["E-mail us"],"p5i1");
stIT("p7i3",["Contact us"],"p5i1");
stIT("p7i4",["Leave a comment"],"p5i1");
stES();
stIT("p0i5",["转移变更"],"p0i1");
stBS("p8",[],"p0");
stIT("p8i0",["内容1",""],"p5i1");
stIT("p8i1",["内容2"],"p8i0");
stES();
stIT("p0i6",["退款模块",,,,,"images/file_c.gif","images/file_c.gif"],"p0i1");
stES();
stEM();
